name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies and build layer
        run: |
          pip install -r requirements.txt -t python
          zip -r9 python.zip ./python

      - name: Package fuction code and layer
        run: |
          zip -r function.zip source/*
          zip -g function.zip python.zip

      - name: Deploy Lambda function with layer
        run: |
          aws lambda update-function-code \
            --function-name gitRepoTest \
            --zip-file fileb://function.zip \
            --publish
          aws lambda update-function-configuration \
            --function-name gitRepoTest \
            --layers arn:aws:lambda:us-east-1:684741729356:layer:testLayer:1