name: deploy to lambda
on:
  push:
    branches:
      - main
      - test
jobs:
  env-setting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
  
  upload-lambda:
    runs-on: ubuntu-latest
    needs: [ env-setting ]
    step:
      - name: Install dependencies and build layer
        run: |
          python -m pip install --upgrade pip
          pip install -r source/micehubUpload/requirements.txt -t python
          zip -r9 python.zip ./python

      - name: Package function code
        run: |
          cd source/micehubUpload
          zip -r ../micehubUpload.zip ./*
          cd ../..

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name gitRepoTest \
            --zip-file fileb://source/micehubUpload.zip \
            --publish

      - name: Deploy Lambda layer
        run: |
          echo "latest_layer_arn=$(aws lambda publish-layer-version \
            --layer-name testLayer \
            --zip-file fileb://soure/micehubUpload/python.zip \
            --compatible-runtimes python3.9 \
            --query 'LayerVersionArn' \
            --output text)" >> $GITHUB_ENV
      
      - name: Connect Lambda function and layer
        run: |
          aws lambda update-function-configuration \
            --function-name gitRepoTest \
            --layers ${{ env.latest_layer_arn }}
    
  thumb-lambda:
    runs-on: ubuntu-latest
    needs: [ env-setting ]

